export const CREATE_REVIEW_PRODUCT_REQUEST = "CREATE_REVIEW_PRODUCT_REQUEST";
export const CREATE_REVIEW_PRODUCT_SUCCESS = "CREATE_REVIEW_PRODUCT_SUCCESS";
export const CREATE_REVIEW_PRODUCT_FAILURE = "CREATE_REVIEW_PRODUCT_FAILURE";

export const DELETE_REVIEW_PRODUCT_REQUEST = "DELETE_REVIEW_PRODUCT_REQUEST";
export const DELETE_REVIEW_PRODUCT_SUCCESS = "DELETE_REVIEW_PRODUCT_SUCCESS";
export const DELETE_REVIEW_PRODUCT_FAILURE = "DELETE_REVIEW_PRODUCT_FAILURE";
