export const ADD_ITEM_TO_CART_REQUEST = "ADD_ITEM_TO_CART_REQUEST";
export const ADD_ITEM_TO_CART_SUCCESS = "ADD_ITEM_TO_CART_SUCCESS";
export const ADD_ITEM_TO_CART_FAILURE = "ADD_ITEM_TO_CART_FAILURE";

export const GET_CART_REQUEST = "GET_CART_REQUEST";
export const GET_CART_SUCCESS = "GET_CART_SUCCESS";
export const GET_CART_FAILURE = "GET_CART_FAILUTRE";

export const REMOVE_ITEM_CART_REQUEST = "REMOVE_ITEM_CART_REQUEST";
export const REMOVE_ITEM_CART_SUCCESS = "REMOVE_ITEM_CART_SUCCESS";
export const REMOVE_ITEM_CART_FAILURE = "REMOVE_ITEM_CART_FAILURE";

export const UPDATE_ITEM_CART_REQUEST = "UPDATE_ITEM_CART_REQUEST";
export const UPDATE_ITEM_CART_SUCCESS = "UPDATE_ITEM_CART_SUCCESS";
export const UPDATE_ITEM_CART_FAILURE = "UPDATE_ITEM_CART_FAILURE";
